### ISSUE TITLE
Inventory.

### ISSUE THREAD

**Issue by ineveraskedforthis** [Calandiel/SongsOfGPL#120]
Character screen should show your inventory.

**Comment by Calandiel** [comment]
If we add equipment itll get dangerously close to your mmo : P

**Comment by ineveraskedforthis** [comment]
It's not about items, but about trade goods you are carrying.

**Comment by Calandiel** [comment]
The line between the two is thin and we likely need both for magic and such, no?

**Comment by ineveraskedforthis** [comment]
That's true. For now this issue is focused on trade goods only to avoid scope creep.

**Comment by Calandiel** [comment]
Yup
