### ISSUE TITLE
Collapsed view for tile inspector.

### ISSUE THREAD

**Issue by ineveraskedforthis** [Calandiel/SongsOfGPL#136]
Currently tile inspector is quite large and obstructs the view whenever you click the tile.
Add a checkbox to the top bar of tile inspector which toggles collapsed mode.
In collapsed mode, only top bar is visible on the bottom of the screen.

**Comment by Calandiel** [comment]
What's the purpose of this? Why not just close the inspector?

**Comment by ineveraskedforthis** [comment]
Purpose is to allow player to access crucial information about provinces and common actions with province without huge window obstructing 1/3 of the screen.
For example, sometimes I just want to check population/realms/other stats of various provinces by clicking around while being zoomed out. Or jump between characters of different realms in observer mode. Huge window makes this process quite uncomfortable while most of data presented in tile inspector doesn't offer anything of use during this process. If you close inspector, there is no way to access important data/actions.

**Comment by Calandiel** [comment]
If you collapse the inspector, you cant access important data/actions either.
This seems like a bandaid for what is an inspector design issue.

What you describe as "collapsed" should be the default and getting "full" information should be the special state.

Our inspector def. is too large and contains too much data. Courtesy of sote's community constantly asking for more data, likely induced by lack of gameplay until now.

I'd redesign the inspector instead. I'll look into making a penpot project for it if you give me 20h

**Comment by ineveraskedforthis** [comment]
Okay, sure.  Yes, it was supposed to be a bandaid for flaws of current tile inspector. For the reference, this is how my idea of collapsed tile-inspector looked like:
![collapsed](https://github.com/Calandiel/SongsOfGPL/assets/19423454/dd0ebcb0-3413-4773-b5cc-def4b6e00e49)
![full](https://github.com/Calandiel/SongsOfGPL/assets/19423454/ec052619-619e-4251-886f-4bc66ffe5cf4)

**Comment by Calandiel** [comment]
Note that the amount of data that can be displayed in such a small ui widget could also be put in a tooltip, with less ui state to be kept of and managed.
Is there a reason why a tooltip cant handle this? The only advantage I see is having access to additional buttons but it doesnt seen like an advantage given that you need to click on a tile to change the collapsed inspector anyway so even with an uncollapsed view you dont cut any mouse clicks.

Moreover, is this a development problem or a gameplay problem that its being solved?

**Comment by ineveraskedforthis** [comment]
It's a UX problem. It's not about decreasing amount of clicks directly but about reducing dead space which is obstructing active space and often causes more clicks or frustration: when you are zoomed out, tile inspector is hovering almost half of the planet! Most importantly, it obstructs area around the center: the area which is expected to be clickable. It means that in order to click a province you need to either
1) Close tile inspector, click province.
2) Rotate the camera so needed provinces are in top/right strip of screen space and click the province.


1 causes constant flickering of huge window opening and closing and requires double amount of clicks
2 is not comfortable because of unusual  shape of active zone: in EU4, for example, this method is okay because their province view is really small and central point is not obstructed.
Personally for me, this quite simple (one boolean flag and few conditions) bandaid reduces frustration caused by province polling loop. Redesigned tile inspector will work as well.

**Comment by Calandiel** [comment]
I think the core of the issue is here (just as you said, most importantly):
```
Most importantly, it obstructs area around the center: the area which is expected to be clickable. It means that in order to click a province you need to either

    Close tile inspector, click province.
    Rotate the camera so needed provinces are in top/right strip of screen space and click the province.
```
If you look at most grand strategy games, their UI widgets are vertical, not horizontal, which is unlike the tile inspector.
I don't think this is accidental given that most common aspect ratio is 16 : 9.

My concern with simple bandaids is that they stop being simple once you have 50 of them and we most definitely will encounter more than that over time.

How about moving the horizontal list of tabs with tile inspector widgets to the left and making it a vertical list of tabs, then rearranging the widgets within existing tabs into a vertical layout? I believe this would make some of the line graphs more readable too as they were originally conceived by SotEs old UI designer to be on a much less wide widget.

**Comment by Calandiel** [comment]
To continue on the previous thought, I think a good starting point would be seeing how large the province view is in EU4 and not making the tile inspector (relatively to the screen size) any bigger than that.

**Comment by ineveraskedforthis** [comment]
Problematic widgets are:
1) POPs widget: same problem as Market tab: it is very space hungry and if we are going to expand pops, then it will require even more space. Probably should be given Market treatment and moved outside of Tile inspector.
2) Geography group of widgets: Geology, Ecology and Climate. They have an opposite problem: they are half empty and probably should be united into Geography tab.
3) Buildings and technology widgets: They have two scroll-able lists side by side. Stacking them vertically will create another source of 4-entry lists.

**Comment by Calandiel** [comment]
Do we need to show all buildings and tech at the same time? EU4 has a expandable view thats collapsed by default for, say, institutions.

Also, wrt buildings, we do not need two list for them. Embed the construction button into the main list and get rid of that list

**Comment by Calandiel** [comment]
Do we close this one now? @ineveraskedforthis 

I don't think it's needed anymore (I'm gonna hit the bed soon so close it if you think it's not relevant anymore too)

**Comment by ineveraskedforthis** [comment]
Closed.
