### ISSUE TITLE
Sorry me again, had a question on how I can generate different landmasses

### ISSUE THREAD

**Issue by GoatQueerEnjoysChocolate** [Calandiel/SongsOfGPL#142]
I don't really know how to generate new landmasses or if it is even possible, and I don't know if I should touch 
`local disable_plate_gen = true`
Since I don't know why it was disabled for this version.
Also why does it keep making the same map?

**Comment by Calandiel** [comment]
There is no world gen support in this repo, that part of the codebase couldn't be licensed under GPL for a variety of reasons. See #94
