### ISSUE TITLE
Use racial variables in economy calculations.

### ISSUE THREAD

**Issue by ineveraskedforthis** [Calandiel/SongsOfGPL#148]
Races have variables:
```
		female_worker_efficiency = 2,
		female_artisan_efficiency = 2,
		female_clerk_efficiency = 2,
		female_ruler_efficiency = 2,

		male_worker_efficiency = 2,
		male_artisan_efficiency = 2,
		male_clerk_efficiency = 2,
		male_ruler_efficiency = 2,
```
They are currently not used but could provide an interesting distinction between races.

**Comment by Calandiel** [comment]
This should be changed into a table that takes in a pop type enum and gives efficiency. Additionally, buildings should define pops they use.

**Comment by Calandiel** [comment]
Also, they should impact efficiency not just throughput, otherwise comparative advantage won't lead to businesses closing due to better suitable races doing things over the locals
